# Generated by Django 3.1.2 on 2020-10-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_auto_20201013_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlalgorithmstatus',
            old_name='parent_mlalgoirthm',
            new_name='parent_mlalgorithm',
        ),
    ]
